language: node_js
node_js:
  - node
install:
  - yarn install
before_deploy:
  - yarn build
deploy:
  - provider: s3
    access_key_id: '$AWS_KEY'
    secret_access_key: '$AWS_SECRET'
    bucket: '$S3_BUCKET'
    acl: public_read
    local-dir: public
    skip_cleanup: true
    cache_control: max-age=300
    on:
      branch: master
